version: '3'
services:
  web:
    build: .
    env_file: .env
    restart: on-failure
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./:/app

  database:
    image: "postgres:12.2"
    env_file: .env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./:/app
    ports:
        - 5432:5432

volumes:
  database-data:
